package com.carrack.track.enums;

public enum AuditAction {
    REGISTER,
    LOGIN,
    LOGOUT,
    USER_CREATED,
    USER_UPDATED,
    USER_SUSPENDED,
    USER_RESTORED,
    USER_DELETED,
    VEHICLE_CREATED,
    VEHICLE_UPDATED,
    VEHICLE_DELETED,
    SERVICE_CREATED,
    SERVICE_UPDATED,
    SERVICE_DELETED,
    REMINDER_CREATED,
    REMINDER_UPDATED,
    REMINDER_DELETED
}
